In [1]:
from ml_config import *

In [2]:
sample = pd.read_csv('../data/01. final_sample', index_col = 0)

In [3]:
store_month = sample.pivot_table(index=['year','month'],columns='store_nbr',values='units',aggfunc=np.sum)

In [22]:
sales = pd.read_csv('../data/train.csv', parse_dates=['date'])
keys = pd.read_csv('../data/key.csv')
weather = pd.read_csv('../data/weather.csv',parse_dates=['date'])
df_1 = pd.merge(weather,keys)
df_1 = pd.merge(df_1, sales)

dates = df_1['date'].dt
df_1['year'] = dates.year
df_1['month'] = dates.month
df_1['day'] = dates.day

In [23]:
df_1.head()

station_nbr       date tmax tmin tavg depart dewpoint wetbulb heat cool  \
0            1 2012-01-01   52   31   42      M       36      40   23    0   
1            1 2012-01-01   52   31   42      M       36      40   23    0   
2            1 2012-01-01   52   31   42      M       36      40   23    0   
3            1 2012-01-01   52   31   42      M       36      40   23    0   
4            1 2012-01-01   52   31   42      M       36      40   23    0   

  ... sealevel resultspeed resultdir avgspeed store_nbr item_nbr units  year  \
0 ...    29.92         3.6        20      4.6         1        1     0  2012   
1 ...    29.92         3.6        20      4.6         1        2     0  2012   
2 ...    29.92         3.6        20      4.6         1        3     0  2012   
3 ...    29.92         3.6        20      4.6         1        4     0  2012   
4 ...    29.92         3.6        20      4.6         1        5     0  2012   

  month day  
0     1   1  
1     1   1  
2     1   1  
3     1   1  
4     1   1  

[5 rows x 26 columns]

In [36]:
# 7번 가게의 13, 14년도 5월에서 9월까지가 비슷함
store_7 = df_1[df_1['store_nbr']==7]

In [27]:
station_6 = df_1[df_1['station_nbr']==6]
station_6['store_nbr'].unique()
# 6번 관측소는 7번, 13번 지점을 관리한다

array([ 7, 13], dtype=int64)

In [45]:
# 7번 13번 지점의 2013년, 2014년 units그래프가 비슷하다
# 다만 7번은 13,14년과 12년 그래프가 붙어있는 반면
# 13번은 13,14년과 12년 그래프가 떨어져있다
# 일단 item_nbr로 13, 14년도에 뭐가 팔렸는지 조사함
store_13 = df_1[df_1['store_nbr']==13]

# store_7 = store_7[store_7['units']!=0]
# store_7 = store_7[(store_7['year']==2013) | (store_7['year']==2014)]

store_7 = store_7[(store_7['year']==2013) | (store_7['year']==2014)]
store_7 = store_7[store_7['units']!=0]

store_13 = store_13[(store_13['year']==2013) | (store_13['year']==2013)]
store_13 = store_13[store_13['units']!=0]

store_7['item_nbr'].unique(), store_13['item_nbr'].unique()

(array([ 5,  7, 23, 93, 95], dtype=int64),
 array([  5,  36,  93, 104], dtype=int64))

# 13, 14년도
# 7번, 13번 가게에서
# 5번, 93번 아이템이 동시에 팔림

In [ ]:
store_7_2013
store_7_2014

store_13_2013
store_13_2014