In [1]:
from jw_package import *
from filling_missing import *

import configuration completed !
train + key + weather merging started
train + key + weather merging finished
function configuration completed ! 
Good to go !


# 1. weather_v4
# 2. 전체 item, 한번이라도 팔린 item
# 3. VIF로 상관관계 높은 애들은 제거
# 4. 전체 store vs 각 store별

# 전체 item + 전체 store = 0.023
# 한번이라도 팔린 item + 전체 store = 0.052
# 전체 item + 각 store별 = 0.055
# 한번이라도 팔린 item + 각 store별 = 0.055

In [2]:
file_path = '../data/weather_v4_delete_nan.csv'

In [3]:
sales = pd.read_csv('../data/basic/train.csv')
keys = pd.read_csv('../data/basic/key.csv')
raw = pd.read_csv(file_path,index_col=0)

In [4]:
category = ['station_nbr','date','sunset','sunrise','codesum']
for each in category:
    raw.drop(each, axis=1, inplace=True)

In [5]:
def vif(dfX0):
    from statsmodels.stats.outliers_influence import variance_inflation_factor
    vif = pd.DataFrame()
    vif["vif"] = [variance_inflation_factor(dfX0.values, i) for i in range(dfX0.shape[1])]
    vif["features"] = dfX0.columns
    vif.sort_values(by='vif',ascending=False, inplace=True)
    
    return vif

In [6]:
vif(raw)

vif     features
2   117092.437701         tavg
6     2378.669838         heat
0     1466.235737         tmax
1     1333.500203         tmin
7     1143.289048         cool
5      305.233940      wetbulb
4       93.737935     dewpoint
14       9.053081     avgspeed
12       8.285885  resultspeed
11       1.944836     sealevel
10       1.598047  stnpressure
3        1.360865       depart
9        1.213874  preciptotal
8        1.140472     snowfall
13       1.129266    resultdir

In [7]:
raw.drop('tavg',axis=1,inplace=True)

In [8]:
vif(raw)

vif     features
10  33632.549986     sealevel
0    9454.480741         tmax
9    7905.857122  stnpressure
1    5054.941832         tmin
4    4001.517307      wetbulb
5    1407.669991         heat
3     812.545662     dewpoint
6     676.589373         cool
13     44.161470     avgspeed
11     27.660894  resultspeed
12      5.343128    resultdir
2       1.357651       depart
8       1.320880  preciptotal
7       1.145985     snowfall

In [9]:
raw.drop('sealevel',axis=1,inplace=True)

In [10]:
vif(raw)

vif     features
9   6039.418195  stnpressure
4   4001.434512      wetbulb
0   2488.900477         tmax
1   1313.112175         tmin
3    809.161112     dewpoint
5    331.328556         heat
6    159.130837         cool
12    44.058922     avgspeed
10    27.632720  resultspeed
11     5.253361    resultdir
2      1.327963       depart
8      1.313331  preciptotal
7      1.142078     snowfall

In [11]:
raw.drop('stnpressure',axis=1,inplace=True)

In [12]:
vif(raw)

vif     features
4   3944.889180      wetbulb
3    805.374678     dewpoint
0    569.999580         tmax
1    400.183530         tmin
11    40.616019     avgspeed
9     26.963933  resultspeed
6      5.808359         cool
10     5.253254    resultdir
5      3.587753         heat
2      1.312596       depart
8      1.310655  preciptotal
7      1.142074     snowfall

In [13]:
raw.drop('wetbulb',axis=1,inplace=True)

In [14]:
vif(raw)

vif     features
1   174.029973         tmin
3   100.280938     dewpoint
0    81.485385         tmax
10   40.615662     avgspeed
8    26.944995  resultspeed
9     5.253200    resultdir
5     3.999480         cool
4     2.710327         heat
7     1.307746  preciptotal
2     1.276115       depart
6     1.125234     snowfall

In [15]:
raw.drop('tmin',axis=1,inplace=True)

In [16]:
vif(raw)

vif     features
0  59.427277         tmax
2  49.891178     dewpoint
9  40.031875     avgspeed
7  26.938350  resultspeed
8   5.246590    resultdir
4   3.057162         cool
3   2.582002         heat
6   1.307729  preciptotal
1   1.265004       depart
5   1.125112     snowfall

In [17]:
raw.drop('tmax',axis=1,inplace=True)

In [18]:
vif(raw)

vif     features
8  37.626148     avgspeed
6  25.962837  resultspeed
1   8.754475     dewpoint
7   4.842350    resultdir
3   2.996776         cool
2   2.485645         heat
0   1.264291       depart
5   1.195056  preciptotal
4   1.118431     snowfall

In [19]:
raw.drop('avgspeed',axis=1,inplace=True)

In [20]:
vif(raw)

vif     features
1  7.468124     dewpoint
7  4.775099    resultdir
6  3.373066  resultspeed
3  2.972165         cool
2  2.351603         heat
0  1.248090       depart
5  1.169672  preciptotal
4  1.118247     snowfall

In [21]:
raw.corr()

depart  dewpoint      heat      cool  snowfall  preciptotal  \
depart       1.000000  0.345256 -0.370535  0.254536 -0.072030    -0.036698   
dewpoint     0.345256  1.000000 -0.884975  0.716079 -0.175647     0.143519   
heat        -0.370535 -0.884975  1.000000 -0.523160  0.263333    -0.053341   
cool         0.254536  0.716079 -0.523160  1.000000 -0.078729    -0.017259   
snowfall    -0.072030 -0.175647  0.263333 -0.078729  1.000000     0.112070   
preciptotal -0.036698  0.143519 -0.053341 -0.017259  0.112070     1.000000   
resultspeed  0.112077 -0.093399  0.082460 -0.003371  0.060029    -0.021580   
resultdir   -0.012858 -0.259576  0.218716 -0.172749 -0.017857    -0.046212   

             resultspeed  resultdir  
depart          0.112077  -0.012858  
dewpoint       -0.093399  -0.259576  
heat            0.082460   0.218716  
cool           -0.003371  -0.172749  
snowfall        0.060029  -0.017857  
preciptotal    -0.021580  -0.046212  
resultspeed     1.000000   0.114156  
resultdir       0.114156   1.000000

In [22]:
trimmed = raw

In [23]:
trimmed.head()

depart  dewpoint  heat  cool  snowfall  preciptotal  resultspeed  resultdir
1    16.0      37.0  24.0   0.0       0.0         0.07          9.1       23.0
2     9.0      24.0  20.0   0.0       0.0         0.00          9.9       31.0
3     4.0      28.0  10.0   0.0       0.0         0.00          8.0       35.0
4     0.0      31.0  16.0   0.0       0.0         0.00         14.0       36.0
9     7.0      54.0   5.0   0.0       0.0         0.00          4.6       23.0

In [25]:
raw = pd.read_csv(file_path,index_col=0)
trimmed['station_nbr'] = raw['station_nbr']
trimmed['date'] = raw['date']

In [26]:
data = sales.merge(keys).merge(trimmed)

In [33]:
data.columns

Index(['date', 'store_nbr', 'item_nbr', 'units', 'station_nbr', 'depart',
       'dewpoint', 'heat', 'cool', 'snowfall', 'preciptotal', 'resultspeed',
       'resultdir'],
      dtype='object')

In [38]:
cols = list(data.columns[3:])
cols.remove('station_nbr')

In [42]:
formula = columns_to_relation(cols,None,'units',False)

In [43]:
formula

'units ~ depart + dewpoint + heat + cool + snowfall + preciptotal + resultspeed + resultdir'

In [109]:
import math

In [204]:
results=[0,]
mean = 0
n = 0
for item_nbr in range(1,112):
    frame = data[data['item_nbr']==item_nbr]
    
    model = sm.OLS.from_formula(formula,data=frame)
    
    r2 = model.fit().rsquared
    
    if not np.isnan(r2):
#         print(item_nbr, r2)
        mean+=r2
        n+=1
    
    if r2>=0.3:
        print(item_nbr,r2)
    
    results.append(model)

d:\anaconda\lib\site-packages\statsmodels\regression\linear_model.py:1386: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss


In [205]:
mean/n

0.023125162160689081

In [88]:
no_zero = data.copy()

In [168]:
stores = data['store_nbr'].unique()
stores

array([ 2,  6, 38, 42,  7, 13,  8, 12, 43, 16, 19, 21, 29, 33, 30, 36], dtype=int64)

In [189]:
from functools import reduce

In [220]:
no_zero = data.copy()
result=[]
print(stores)
for store in list(stores):
    item_nbr = data[(data['store_nbr']==store) & (data['units']!=0)]
    this_stores_items = item_nbr['item_nbr'].unique()
    print(store, this_stores_items)
    for each in list(this_stores_items):
        tok = no_zero[(no_zero['store_nbr']==store) & (no_zero['item_nbr']==each)]
        result.append(tok)
      
no_zero = reduce((lambda x,y : x.append(y)), result)

[ 2  6 38 42  7 13  8 12 43 16 19 21 29 33 30 36]
2 [ 5 44 11 85 93]
6 [  9  45  14 107]
38 [ 9 45 52 93 86 98]
42 [ 5 45 82]
7 [ 5  7 23 93 95]
13 [  5  36  46  93 104]
8 [  5  23  59  93  84 100]
12 [16 37 79 93 86]
43 [ 16  37  73  93   3 105]
16 [16 25 39 50 85 93 77 64]
19 [16 83 39 69 93 88 75 15]
21 [  5  44  91 109]
29 [ 8 41 45 56]
33 [ 9 44 85 92 93]
30 [16 44 49 51 65 13]
36 [ 9 44 30  1]


In [231]:
results=[0,]
mean = 0
n = 0
print(no_zero['item_nbr'].unique())
for item_nbr in no_zero['item_nbr'].unique():
    frame = no_zero[no_zero['item_nbr']==item_nbr]
    
    model = sm.OLS.from_formula(formula,data=frame)
    
    r2 = model.fit().rsquared
    
    if not np.isnan(r2):
        mean+=r2
        n+=1
        
        if r2>=0.3:
            print(item_nbr, r2)
    
    results.append(model)

[  5  44  11  85  93   9  45  14 107  52  86  98  82   7  23  95  36  46
 104  59  84 100  16  37  79  73   3 105  25  39  50  77  64  83  69  88
  75  15  91 109   8  41  56  92  49  51  65  13  30   1]
51 0.367533449079


In [222]:
mean/n

0.051996741733116678

In [233]:
results=[0,]
mean = 0
n = 0
print(data['store_nbr'].unique())
for store_nbr in data['store_nbr'].unique():
    store = data[data['store_nbr']==store_nbr]
    
    store_result=[]
    
    for item_nbr in store['item_nbr'].unique():
        
        frame = store[store['item_nbr']==item_nbr]
        
        model = sm.OLS.from_formula(formula,data=frame)
        
        r2 = model.fit().rsquared
        
        if not np.isnan(r2):
            print(store_nbr, item_nbr, r2)
            mean+=r2
            n+=1
        
        store_result.append(model)
        
    results.append(store_result)
    


[ 2  6 38 42  7 13  8 12 43 16 19 21 29 33 30 36]
2 5 0.0166832798794
2 11 0.0324951906938


d:\anaconda\lib\site-packages\statsmodels\regression\linear_model.py:1386: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss


2 44 0.0223677173196
2 85 0.203385264126
2 93 0.0426525415065
6 9 0.0181630782596
6 14 0.0402874488433
6 45 0.0243583892253
6 107 0.0286848186941
38 9 0.0261419858789
38 45 0.0402380686976
38 52 0.0137507497572
38 86 0.0461688603344
38 93 0.0528890719762
38 98 0.081622147019
42 5 0.018132173347
42 45 0.0659452684734
42 82 0.0297115432703
7 5 0.029626625298
7 7 0.00424921957501
7 23 0.0153993877589
7 93 0.0559144544332
7 95 0.0643063228232
13 5 0.0419337446472
13 36 0.04145079318
13 46 0.0176918573791
13 93 0.0360802918422
13 104 0.0697509759059
8 5 0.0667322262608
8 23 0.0192746694873
8 59 0.00682582472939
8 84 0.0262208168794
8 93 0.0292965735565
8 100 0.0167202738352
12 16 0.058094178884
12 37 0.034195521871
12 79 0.010827390439
12 86 0.0196269715165
12 93 0.130942807645
43 3 0.0868362188102
43 16 0.0787510053223
43 37 0.0796878973795
43 73 0.0223112525484
43 93 0.0385744832299
43 105 0.00370158070769
16 16 0.0732349827087
16 25 0.0356628215183
16 39 0.138199720926
16 50 0.0891489393

In [162]:
mean/n

0.055101314046342657

In [234]:
results=[0,]
mean = 0
n = 0
print(no_zero['store_nbr'].unique())
for store_nbr in no_zero['store_nbr'].unique():
    store = no_zero[no_zero['store_nbr']==store_nbr]
    
    store_result=[]
    
    print(store_nbr, store['item_nbr'].unique())
    
    for item_nbr in store['item_nbr'].unique():
        
        frame = store[store['item_nbr']==item_nbr]
        
        model = sm.OLS.from_formula(formula,data=frame)
        
        r2 = model.fit().rsquared
        
        if not np.isnan(r2):
            print(store_nbr, item_nbr, r2)
            mean+=r2
            n+=1
        
        store_result.append(model)
        
    results.append(store_result)
    


[ 2  6 38 42  7 13  8 12 43 16 19 21 29 33 30 36]
2 [ 5 44 11 85 93]
2 5 0.0166832798794
2 44 0.0223677173196
2 11 0.0324951906938
2 85 0.203385264126
2 93 0.0426525415065
6 [  9  45  14 107]
6 9 0.0181630782596
6 45 0.0243583892253
6 14 0.0402874488433
6 107 0.0286848186941
38 [ 9 45 52 93 86 98]
38 9 0.0261419858789
38 45 0.0402380686976
38 52 0.0137507497572
38 93 0.0528890719762
38 86 0.0461688603344
38 98 0.081622147019
42 [ 5 45 82]
42 5 0.018132173347
42 45 0.0659452684734
42 82 0.0297115432703
7 [ 5  7 23 93 95]
7 5 0.029626625298
7 7 0.00424921957501
7 23 0.0153993877589
7 93 0.0559144544332
7 95 0.0643063228232
13 [  5  36  46  93 104]
13 5 0.0419337446472
13 36 0.04145079318
13 46 0.0176918573791
13 93 0.0360802918422
13 104 0.0697509759059
8 [  5  23  59  93  84 100]
8 5 0.0667322262608
8 23 0.0192746694873
8 59 0.00682582472939
8 93 0.0292965735565
8 84 0.0262208168794
8 100 0.0167202738352
12 [16 37 79 93 86]
12 16 0.058094178884
12 37 0.034195521871
12 79 0.010827390439


In [224]:
mean/n

0.055101314046342657

In [153]:
tmp['item_nbr'].unique()

array([  9,  45,  14, 107], dtype=int64)